# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0acdf14f3d85f49c166ea1ce554059e74766898d92e30f01244fa8503ca5ef86d33852f6e6002c6b49b8457815949f9fc81bcaa56ee3443c617e75acc52e0b1

test:
  secret_key_base: 4939113ae56e2deb5f188cde33dd74d5db78d33eedbf375a5aa7ecd7ca07b8d9087a9829806180d2159ddfbbb6da2921d39c08b9d0a216ba89af711cef2ec2f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
